import Head from 'next/head';
import Header from './components/header';
import Hero from './components/hero';
import SubHero from './components/subHero';
import About from './components/about';
import Different from './components/different';
import How from './components/how';
import Who from './components/who';
import Proof from './components/proof';
import Contact from './components/contact';
import Footer from './components/footer';
import Schedule from './components/schedule';

export default function Home() {
  return (
    <div>
      <Head>
        <title>High Rank Local</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
      <SubHero />
      <About />
      <Different />
      <How />
      <Who />
      <Proof />
      <Contact />
      <Schedule />
      <Footer />

    </div>
  )
}
